package com.minhafazenda.model;
// Generated 13/08/2015 12:46:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Animal generated by hbm2java
 */
public class Animal  implements java.io.Serializable {


     private Integer id;
     private Animal animalByIdPai;
     private Animal animalByIdMae;
     private Categoria categoria;
     private GrauSangue grauSangue;
     private PropriedadeRural propriedadeRural;
     private Raca raca;
     private String nome;
     private Character sexo;
     private Date dataNascimento;
     private Integer numeroBotton;
     private Integer tipoRegistro;
     private Set vacinaAnimals = new HashSet(0);
     private Set animalsForIdPai = new HashSet(0);
     private Set animalsForIdMae = new HashSet(0);
     private Set producaoLeites = new HashSet(0);
     private Set fotoses = new HashSet(0);

    public Animal() {
    }

	
    public Animal(Categoria categoria, GrauSangue grauSangue, PropriedadeRural propriedadeRural, Raca raca, String nome) {
        this.categoria = categoria;
        this.grauSangue = grauSangue;
        this.propriedadeRural = propriedadeRural;
        this.raca = raca;
        this.nome = nome;
    }
    public Animal(Animal animalByIdPai, Animal animalByIdMae, Categoria categoria, GrauSangue grauSangue, PropriedadeRural propriedadeRural, Raca raca, String nome, Character sexo, Date dataNascimento, Integer numeroBotton, Integer tipoRegistro, Set vacinaAnimals, Set animalsForIdPai, Set animalsForIdMae, Set producaoLeites, Set fotoses) {
       this.animalByIdPai = animalByIdPai;
       this.animalByIdMae = animalByIdMae;
       this.categoria = categoria;
       this.grauSangue = grauSangue;
       this.propriedadeRural = propriedadeRural;
       this.raca = raca;
       this.nome = nome;
       this.sexo = sexo;
       this.dataNascimento = dataNascimento;
       this.numeroBotton = numeroBotton;
       this.tipoRegistro = tipoRegistro;
       this.vacinaAnimals = vacinaAnimals;
       this.animalsForIdPai = animalsForIdPai;
       this.animalsForIdMae = animalsForIdMae;
       this.producaoLeites = producaoLeites;
       this.fotoses = fotoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Animal getAnimalByIdPai() {
        return this.animalByIdPai;
    }
    
    public void setAnimalByIdPai(Animal animalByIdPai) {
        this.animalByIdPai = animalByIdPai;
    }
    public Animal getAnimalByIdMae() {
        return this.animalByIdMae;
    }
    
    public void setAnimalByIdMae(Animal animalByIdMae) {
        this.animalByIdMae = animalByIdMae;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public GrauSangue getGrauSangue() {
        return this.grauSangue;
    }
    
    public void setGrauSangue(GrauSangue grauSangue) {
        this.grauSangue = grauSangue;
    }
    public PropriedadeRural getPropriedadeRural() {
        return this.propriedadeRural;
    }
    
    public void setPropriedadeRural(PropriedadeRural propriedadeRural) {
        this.propriedadeRural = propriedadeRural;
    }
    public Raca getRaca() {
        return this.raca;
    }
    
    public void setRaca(Raca raca) {
        this.raca = raca;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public Integer getNumeroBotton() {
        return this.numeroBotton;
    }
    
    public void setNumeroBotton(Integer numeroBotton) {
        this.numeroBotton = numeroBotton;
    }
    public Integer getTipoRegistro() {
        return this.tipoRegistro;
    }
    
    public void setTipoRegistro(Integer tipoRegistro) {
        this.tipoRegistro = tipoRegistro;
    }
    public Set getVacinaAnimals() {
        return this.vacinaAnimals;
    }
    
    public void setVacinaAnimals(Set vacinaAnimals) {
        this.vacinaAnimals = vacinaAnimals;
    }
    public Set getAnimalsForIdPai() {
        return this.animalsForIdPai;
    }
    
    public void setAnimalsForIdPai(Set animalsForIdPai) {
        this.animalsForIdPai = animalsForIdPai;
    }
    public Set getAnimalsForIdMae() {
        return this.animalsForIdMae;
    }
    
    public void setAnimalsForIdMae(Set animalsForIdMae) {
        this.animalsForIdMae = animalsForIdMae;
    }
    public Set getProducaoLeites() {
        return this.producaoLeites;
    }
    
    public void setProducaoLeites(Set producaoLeites) {
        this.producaoLeites = producaoLeites;
    }
    public Set getFotoses() {
        return this.fotoses;
    }
    
    public void setFotoses(Set fotoses) {
        this.fotoses = fotoses;
    }




}


