package com.minhafazenda.model;
// Generated 13/08/2015 12:46:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nome;
     private Set propriedadeRurals = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(Estado estado, String nome) {
        this.estado = estado;
        this.nome = nome;
    }
    public Cidade(Estado estado, String nome, Set propriedadeRurals) {
       this.estado = estado;
       this.nome = nome;
       this.propriedadeRurals = propriedadeRurals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getPropriedadeRurals() {
        return this.propriedadeRurals;
    }
    
    public void setPropriedadeRurals(Set propriedadeRurals) {
        this.propriedadeRurals = propriedadeRurals;
    }




}


