package com.minhafazenda.model;
// Generated 18/08/2015 19:49:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,catalog="fazenda"
)
public class Cidade  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nome;
     private Set propriedadeRurals = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(Estado estado, String nome) {
        this.estado = estado;
        this.nome = nome;
    }
    public Cidade(Estado estado, String nome, Set propriedadeRurals) {
       this.estado = estado;
       this.nome = nome;
       this.propriedadeRurals = propriedadeRurals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado_id", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getPropriedadeRurals() {
        return this.propriedadeRurals;
    }
    
    public void setPropriedadeRurals(Set propriedadeRurals) {
        this.propriedadeRurals = propriedadeRurals;
    }




}


