package com.minhafazenda.model;
// Generated 18/08/2015 19:49:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fotos generated by hbm2java
 */
@Entity
@Table(name="fotos"
    ,catalog="fazenda"
)
public class Fotos  implements java.io.Serializable {


     private Integer id;
     private Animal animal;
     private String descricao;
     private String nomeArquivo;

    public Fotos() {
    }

    public Fotos(Animal animal, String descricao, String nomeArquivo) {
       this.animal = animal;
       this.descricao = descricao;
       this.nomeArquivo = nomeArquivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="animal_id", nullable=false)
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }

    
    @Column(name="descricao", nullable=false, length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="nome_arquivo", nullable=false, length=100)
    public String getNomeArquivo() {
        return this.nomeArquivo;
    }
    
    public void setNomeArquivo(String nomeArquivo) {
        this.nomeArquivo = nomeArquivo;
    }




}


