package com.minhafazenda.model;
// Generated 22/11/2015 11:05:37 by Hibernate Tools 4.3.1



/**
 * MfAuditoriaConfiguracao generated by hbm2java
 */
public class MfAuditoriaConfiguracao  implements java.io.Serializable {


     private Integer id;
     private String tabela;
     private String triggerDelete;
     private String triggerInsert;
     private String triggerUpdate;
     private String viewAuditoria;
     private String viewAuditoriaItem;

    public MfAuditoriaConfiguracao() {
    }

    public MfAuditoriaConfiguracao(String tabela, String triggerDelete, String triggerInsert, String triggerUpdate, String viewAuditoria, String viewAuditoriaItem) {
       this.tabela = tabela;
       this.triggerDelete = triggerDelete;
       this.triggerInsert = triggerInsert;
       this.triggerUpdate = triggerUpdate;
       this.viewAuditoria = viewAuditoria;
       this.viewAuditoriaItem = viewAuditoriaItem;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTabela() {
        return this.tabela;
    }
    
    public void setTabela(String tabela) {
        this.tabela = tabela;
    }
    public String getTriggerDelete() {
        return this.triggerDelete;
    }
    
    public void setTriggerDelete(String triggerDelete) {
        this.triggerDelete = triggerDelete;
    }
    public String getTriggerInsert() {
        return this.triggerInsert;
    }
    
    public void setTriggerInsert(String triggerInsert) {
        this.triggerInsert = triggerInsert;
    }
    public String getTriggerUpdate() {
        return this.triggerUpdate;
    }
    
    public void setTriggerUpdate(String triggerUpdate) {
        this.triggerUpdate = triggerUpdate;
    }
    public String getViewAuditoria() {
        return this.viewAuditoria;
    }
    
    public void setViewAuditoria(String viewAuditoria) {
        this.viewAuditoria = viewAuditoria;
    }
    public String getViewAuditoriaItem() {
        return this.viewAuditoriaItem;
    }
    
    public void setViewAuditoriaItem(String viewAuditoriaItem) {
        this.viewAuditoriaItem = viewAuditoriaItem;
    }




}


