package com.minhafazenda.model;
// Generated 22/11/2015 11:05:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MfAuditoria generated by hbm2java
 */
public class MfAuditoria  implements java.io.Serializable {


     private Long id;
     private String usuario;
     private String tabela;
     private String chavePrimaria1;
     private String chavePrimaria2;
     private String acao;
     private Date dataHora;

    public MfAuditoria() {
    }

    public MfAuditoria(String usuario, String tabela, String chavePrimaria1, String chavePrimaria2, String acao, Date dataHora) {
       this.usuario = usuario;
       this.tabela = tabela;
       this.chavePrimaria1 = chavePrimaria1;
       this.chavePrimaria2 = chavePrimaria2;
       this.acao = acao;
       this.dataHora = dataHora;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getTabela() {
        return this.tabela;
    }
    
    public void setTabela(String tabela) {
        this.tabela = tabela;
    }
    public String getChavePrimaria1() {
        return this.chavePrimaria1;
    }
    
    public void setChavePrimaria1(String chavePrimaria1) {
        this.chavePrimaria1 = chavePrimaria1;
    }
    public String getChavePrimaria2() {
        return this.chavePrimaria2;
    }
    
    public void setChavePrimaria2(String chavePrimaria2) {
        this.chavePrimaria2 = chavePrimaria2;
    }
    public String getAcao() {
        return this.acao;
    }
    
    public void setAcao(String acao) {
        this.acao = acao;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }




}


