package com.minhafazenda.model;
// Generated 22/11/2015 11:05:37 by Hibernate Tools 4.3.1



/**
 * MfAuditoriaItem generated by hbm2java
 */
public class MfAuditoriaItem  implements java.io.Serializable {


     private Long idAuditoriaItem;
     private long idAuditoria;
     private String campo;
     private String valorAntigo;
     private String valorNovo;

    public MfAuditoriaItem() {
    }

	
    public MfAuditoriaItem(long idAuditoria, String campo) {
        this.idAuditoria = idAuditoria;
        this.campo = campo;
    }
    public MfAuditoriaItem(long idAuditoria, String campo, String valorAntigo, String valorNovo) {
       this.idAuditoria = idAuditoria;
       this.campo = campo;
       this.valorAntigo = valorAntigo;
       this.valorNovo = valorNovo;
    }
   
    public Long getIdAuditoriaItem() {
        return this.idAuditoriaItem;
    }
    
    public void setIdAuditoriaItem(Long idAuditoriaItem) {
        this.idAuditoriaItem = idAuditoriaItem;
    }
    public long getIdAuditoria() {
        return this.idAuditoria;
    }
    
    public void setIdAuditoria(long idAuditoria) {
        this.idAuditoria = idAuditoria;
    }
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }
    public String getValorAntigo() {
        return this.valorAntigo;
    }
    
    public void setValorAntigo(String valorAntigo) {
        this.valorAntigo = valorAntigo;
    }
    public String getValorNovo() {
        return this.valorNovo;
    }
    
    public void setValorNovo(String valorNovo) {
        this.valorNovo = valorNovo;
    }




}


