package com.minhafazenda.model;
// Generated 13/08/2015 12:46:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set estados = new HashSet(0);

    public Pais() {
    }

	
    public Pais(String nome) {
        this.nome = nome;
    }
    public Pais(String nome, Set estados) {
       this.nome = nome;
       this.estados = estados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set estados) {
        this.estados = estados;
    }




}


