package com.minhafazenda.model;
// Generated 13/08/2015 12:46:09 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProducaoLeite generated by hbm2java
 */
public class ProducaoLeite  implements java.io.Serializable {


     private int id;
     private Animal animal;
     private Date dataHora;
     private Integer quantidadeMl;

    public ProducaoLeite() {
    }

	
    public ProducaoLeite(int id, Animal animal) {
        this.id = id;
        this.animal = animal;
    }
    public ProducaoLeite(int id, Animal animal, Date dataHora, Integer quantidadeMl) {
       this.id = id;
       this.animal = animal;
       this.dataHora = dataHora;
       this.quantidadeMl = quantidadeMl;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }
    public Integer getQuantidadeMl() {
        return this.quantidadeMl;
    }
    
    public void setQuantidadeMl(Integer quantidadeMl) {
        this.quantidadeMl = quantidadeMl;
    }




}


