package com.minhafazenda.model;
// Generated 18/08/2015 19:49:12 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProducaoLeite generated by hbm2java
 */
@Entity
@Table(name="producao_leite"
    ,catalog="fazenda"
)
public class ProducaoLeite  implements java.io.Serializable {


     private int id;
     private Animal animal;
     private Date dataHora;
     private Integer quantidadeMl;

    public ProducaoLeite() {
    }

	
    public ProducaoLeite(int id, Animal animal) {
        this.id = id;
        this.animal = animal;
    }
    public ProducaoLeite(int id, Animal animal, Date dataHora, Integer quantidadeMl) {
       this.id = id;
       this.animal = animal;
       this.dataHora = dataHora;
       this.quantidadeMl = quantidadeMl;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_animal", nullable=false)
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora", length=19)
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }

    
    @Column(name="quantidade_ml")
    public Integer getQuantidadeMl() {
        return this.quantidadeMl;
    }
    
    public void setQuantidadeMl(Integer quantidadeMl) {
        this.quantidadeMl = quantidadeMl;
    }




}


