package com.minhafazenda.model;
// Generated 13/12/2015 15:29:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PropriedadeRural generated by hbm2java
 */
public class PropriedadeRural  implements java.io.Serializable {


     private Integer id;
     private Cidade cidade;
     private String descricao;
     private String endereco;
     private Integer tamanho;
     private String cep;
     private int idUsuarioAlterou;
     private Set usuarioPropriedadeRurals = new HashSet(0);
     private Set animals = new HashSet(0);

    public PropriedadeRural() {
    }

	
    public PropriedadeRural(Cidade cidade, String descricao, int idUsuarioAlterou) {
        this.cidade = cidade;
        this.descricao = descricao;
        this.idUsuarioAlterou = idUsuarioAlterou;
    }
    public PropriedadeRural(Cidade cidade, String descricao, String endereco, Integer tamanho, String cep, int idUsuarioAlterou, Set usuarioPropriedadeRurals, Set animals) {
       this.cidade = cidade;
       this.descricao = descricao;
       this.endereco = endereco;
       this.tamanho = tamanho;
       this.cep = cep;
       this.idUsuarioAlterou = idUsuarioAlterou;
       this.usuarioPropriedadeRurals = usuarioPropriedadeRurals;
       this.animals = animals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Integer getTamanho() {
        return this.tamanho;
    }
    
    public void setTamanho(Integer tamanho) {
        this.tamanho = tamanho;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public int getIdUsuarioAlterou() {
        return this.idUsuarioAlterou;
    }
    
    public void setIdUsuarioAlterou(int idUsuarioAlterou) {
        this.idUsuarioAlterou = idUsuarioAlterou;
    }
    public Set getUsuarioPropriedadeRurals() {
        return this.usuarioPropriedadeRurals;
    }
    
    public void setUsuarioPropriedadeRurals(Set usuarioPropriedadeRurals) {
        this.usuarioPropriedadeRurals = usuarioPropriedadeRurals;
    }
    public Set getAnimals() {
        return this.animals;
    }
    
    public void setAnimals(Set animals) {
        this.animals = animals;
    }




}


