package com.minhafazenda.model;
// Generated 18/08/2015 19:49:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Raca generated by hbm2java
 */
@Entity
@Table(name="raca"
    ,catalog="fazenda"
)
public class Raca  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private String nomeArquivo;
     private Set animals = new HashSet(0);

    public Raca() {
    }

	
    public Raca(String descricao) {
        this.descricao = descricao;
    }
    public Raca(String descricao, String nomeArquivo, Set animals) {
       this.descricao = descricao;
       this.nomeArquivo = nomeArquivo;
       this.animals = animals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descricao", nullable=false, length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="nome_arquivo", length=45)
    public String getNomeArquivo() {
        return this.nomeArquivo;
    }
    
    public void setNomeArquivo(String nomeArquivo) {
        this.nomeArquivo = nomeArquivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="raca")
    public Set getAnimals() {
        return this.animals;
    }
    
    public void setAnimals(Set animals) {
        this.animals = animals;
    }




}


