package com.minhafazenda.model;
// Generated 18/08/2015 19:49:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsuarioTipo generated by hbm2java
 */
@Entity
@Table(name="usuario_tipo"
    ,catalog="fazenda"
)
public class UsuarioTipo  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set usuarios = new HashSet(0);

    public UsuarioTipo() {
    }

	
    public UsuarioTipo(int id) {
        this.id = id;
    }
    public UsuarioTipo(int id, String descricao, Set usuarios) {
       this.id = id;
       this.descricao = descricao;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarioTipo")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


