package com.minhafazenda.model;
// Generated 22/11/2015 11:05:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private UsuarioTipo usuarioTipo;
     private String usuario;
     private String senha;
     private int idUsuarioAlterou;
     private Set vacinaAnimals = new HashSet(0);
     private Set usuarioPropriedadeRurals = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(UsuarioTipo usuarioTipo, int idUsuarioAlterou) {
        this.usuarioTipo = usuarioTipo;
        this.idUsuarioAlterou = idUsuarioAlterou;
    }
    public Usuario(UsuarioTipo usuarioTipo, String usuario, String senha, int idUsuarioAlterou, Set vacinaAnimals, Set usuarioPropriedadeRurals) {
       this.usuarioTipo = usuarioTipo;
       this.usuario = usuario;
       this.senha = senha;
       this.idUsuarioAlterou = idUsuarioAlterou;
       this.vacinaAnimals = vacinaAnimals;
       this.usuarioPropriedadeRurals = usuarioPropriedadeRurals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UsuarioTipo getUsuarioTipo() {
        return this.usuarioTipo;
    }
    
    public void setUsuarioTipo(UsuarioTipo usuarioTipo) {
        this.usuarioTipo = usuarioTipo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public int getIdUsuarioAlterou() {
        return this.idUsuarioAlterou;
    }
    
    public void setIdUsuarioAlterou(int idUsuarioAlterou) {
        this.idUsuarioAlterou = idUsuarioAlterou;
    }
    public Set getVacinaAnimals() {
        return this.vacinaAnimals;
    }
    
    public void setVacinaAnimals(Set vacinaAnimals) {
        this.vacinaAnimals = vacinaAnimals;
    }
    public Set getUsuarioPropriedadeRurals() {
        return this.usuarioPropriedadeRurals;
    }
    
    public void setUsuarioPropriedadeRurals(Set usuarioPropriedadeRurals) {
        this.usuarioPropriedadeRurals = usuarioPropriedadeRurals;
    }




}


