package com.minhafazenda.model;
// Generated 13/12/2015 15:29:49 by Hibernate Tools 4.3.1



/**
 * UsuarioPropriedadeRural generated by hbm2java
 */
public class UsuarioPropriedadeRural  implements java.io.Serializable {


     private UsuarioPropriedadeRuralId id;
     private PropriedadeRural propriedadeRural;
     private Usuario usuario;
     private Integer idUsuarioAlterou;

    public UsuarioPropriedadeRural() {
    }

	
    public UsuarioPropriedadeRural(UsuarioPropriedadeRuralId id, PropriedadeRural propriedadeRural, Usuario usuario) {
        this.id = id;
        this.propriedadeRural = propriedadeRural;
        this.usuario = usuario;
    }
    public UsuarioPropriedadeRural(UsuarioPropriedadeRuralId id, PropriedadeRural propriedadeRural, Usuario usuario, Integer idUsuarioAlterou) {
       this.id = id;
       this.propriedadeRural = propriedadeRural;
       this.usuario = usuario;
       this.idUsuarioAlterou = idUsuarioAlterou;
    }
   
    public UsuarioPropriedadeRuralId getId() {
        return this.id;
    }
    
    public void setId(UsuarioPropriedadeRuralId id) {
        this.id = id;
    }
    public PropriedadeRural getPropriedadeRural() {
        return this.propriedadeRural;
    }
    
    public void setPropriedadeRural(PropriedadeRural propriedadeRural) {
        this.propriedadeRural = propriedadeRural;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getIdUsuarioAlterou() {
        return this.idUsuarioAlterou;
    }
    
    public void setIdUsuarioAlterou(Integer idUsuarioAlterou) {
        this.idUsuarioAlterou = idUsuarioAlterou;
    }




}


