package com.minhafazenda.model;
// Generated 13/12/2015 15:29:49 by Hibernate Tools 4.3.1



/**
 * UsuarioPropriedadeRuralId generated by hbm2java
 */
public class UsuarioPropriedadeRuralId  implements java.io.Serializable {


     private int idUsuario;
     private int idPropriedadeRural;

    public UsuarioPropriedadeRuralId() {
    }

    public UsuarioPropriedadeRuralId(int idUsuario, int idPropriedadeRural) {
       this.idUsuario = idUsuario;
       this.idPropriedadeRural = idPropriedadeRural;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdPropriedadeRural() {
        return this.idPropriedadeRural;
    }
    
    public void setIdPropriedadeRural(int idPropriedadeRural) {
        this.idPropriedadeRural = idPropriedadeRural;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioPropriedadeRuralId) ) return false;
		 UsuarioPropriedadeRuralId castOther = ( UsuarioPropriedadeRuralId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdPropriedadeRural()==castOther.getIdPropriedadeRural());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdPropriedadeRural();
         return result;
   }   


}


