package com.minhafazenda.model;
// Generated 18/08/2015 19:49:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vacina generated by hbm2java
 */
@Entity
@Table(name="vacina"
    ,catalog="fazenda"
)
public class Vacina  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private String modoUso;
     private String indicacoes;
     private String vacinacol;
     private Integer diasValidade;
     private Set vacinaAnimals = new HashSet(0);

    public Vacina() {
    }

    public Vacina(String descricao, String modoUso, String indicacoes, String vacinacol, Integer diasValidade, Set vacinaAnimals) {
       this.descricao = descricao;
       this.modoUso = modoUso;
       this.indicacoes = indicacoes;
       this.vacinacol = vacinacol;
       this.diasValidade = diasValidade;
       this.vacinaAnimals = vacinaAnimals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descricao", length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="modo_uso", length=65535)
    public String getModoUso() {
        return this.modoUso;
    }
    
    public void setModoUso(String modoUso) {
        this.modoUso = modoUso;
    }

    
    @Column(name="indicacoes", length=65535)
    public String getIndicacoes() {
        return this.indicacoes;
    }
    
    public void setIndicacoes(String indicacoes) {
        this.indicacoes = indicacoes;
    }

    
    @Column(name="vacinacol", length=45)
    public String getVacinacol() {
        return this.vacinacol;
    }
    
    public void setVacinacol(String vacinacol) {
        this.vacinacol = vacinacol;
    }

    
    @Column(name="dias_validade")
    public Integer getDiasValidade() {
        return this.diasValidade;
    }
    
    public void setDiasValidade(Integer diasValidade) {
        this.diasValidade = diasValidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vacina")
    public Set getVacinaAnimals() {
        return this.vacinaAnimals;
    }
    
    public void setVacinaAnimals(Set vacinaAnimals) {
        this.vacinaAnimals = vacinaAnimals;
    }




}


