package com.minhafazenda.model;
// Generated 18/08/2015 19:49:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VacinaAnimalId generated by hbm2java
 */
@Embeddable
public class VacinaAnimalId  implements java.io.Serializable {


     private int idVacina;
     private int idAnimal;
     private int sequencia;

    public VacinaAnimalId() {
    }

    public VacinaAnimalId(int idVacina, int idAnimal, int sequencia) {
       this.idVacina = idVacina;
       this.idAnimal = idAnimal;
       this.sequencia = sequencia;
    }
   


    @Column(name="id_vacina", nullable=false)
    public int getIdVacina() {
        return this.idVacina;
    }
    
    public void setIdVacina(int idVacina) {
        this.idVacina = idVacina;
    }


    @Column(name="id_animal", nullable=false)
    public int getIdAnimal() {
        return this.idAnimal;
    }
    
    public void setIdAnimal(int idAnimal) {
        this.idAnimal = idAnimal;
    }


    @Column(name="sequencia", nullable=false)
    public int getSequencia() {
        return this.sequencia;
    }
    
    public void setSequencia(int sequencia) {
        this.sequencia = sequencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VacinaAnimalId) ) return false;
		 VacinaAnimalId castOther = ( VacinaAnimalId ) other; 
         
		 return (this.getIdVacina()==castOther.getIdVacina())
 && (this.getIdAnimal()==castOther.getIdAnimal())
 && (this.getSequencia()==castOther.getSequencia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVacina();
         result = 37 * result + this.getIdAnimal();
         result = 37 * result + this.getSequencia();
         return result;
   }   


}


