package com.minhafazenda.model;
// Generated 18/08/2015 19:49:12 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VacinaAnimal generated by hbm2java
 */
@Entity
@Table(name="vacina_animal"
    ,catalog="fazenda"
)
public class VacinaAnimal  implements java.io.Serializable {


     private VacinaAnimalId id;
     private Animal animal;
     private Usuario usuario;
     private Vacina vacina;
     private Date dataAplicacao;
     private Date dataVencimento;
     private Integer dose;

    public VacinaAnimal() {
    }

	
    public VacinaAnimal(VacinaAnimalId id, Animal animal, Usuario usuario, Vacina vacina) {
        this.id = id;
        this.animal = animal;
        this.usuario = usuario;
        this.vacina = vacina;
    }
    public VacinaAnimal(VacinaAnimalId id, Animal animal, Usuario usuario, Vacina vacina, Date dataAplicacao, Date dataVencimento, Integer dose) {
       this.id = id;
       this.animal = animal;
       this.usuario = usuario;
       this.vacina = vacina;
       this.dataAplicacao = dataAplicacao;
       this.dataVencimento = dataVencimento;
       this.dose = dose;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVacina", column=@Column(name="id_vacina", nullable=false) ), 
        @AttributeOverride(name="idAnimal", column=@Column(name="id_animal", nullable=false) ), 
        @AttributeOverride(name="sequencia", column=@Column(name="sequencia", nullable=false) ) } )
    public VacinaAnimalId getId() {
        return this.id;
    }
    
    public void setId(VacinaAnimalId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_animal", nullable=false, insertable=false, updatable=false)
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vacina", nullable=false, insertable=false, updatable=false)
    public Vacina getVacina() {
        return this.vacina;
    }
    
    public void setVacina(Vacina vacina) {
        this.vacina = vacina;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_aplicacao", length=10)
    public Date getDataAplicacao() {
        return this.dataAplicacao;
    }
    
    public void setDataAplicacao(Date dataAplicacao) {
        this.dataAplicacao = dataAplicacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_vencimento", length=10)
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }

    
    @Column(name="dose")
    public Integer getDose() {
        return this.dose;
    }
    
    public void setDose(Integer dose) {
        this.dose = dose;
    }




}


