/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minhafazenda.view;

import com.minhafazenda.controller.ProducaoLeiteController;
import com.minhafazenda.model.Animal;
import com.minhafazenda.model.ProducaoLeite;
import com.minhafazenda.util.Formatacao;
import com.minhafazenda.util.UsuarioLogado;
import javax.swing.JOptionPane;

/**
 *
 * @author cleverton
 */
public class FrmProducaoLeiteCadastro extends javax.swing.JDialog
{

    private Formatacao formatacao;
    private final ProducaoLeiteController objController;
    private ProducaoLeite objProducaoLeite;
    private boolean edicao;

    private FrmPesquisarAnimal frmPesqAnimal;

    /**
     * Creates new form FrmCategoriaCadastro
     */
    public FrmProducaoLeiteCadastro()
    {
        initComponents();
        //Cria o objeto de controller
        this.objController = new ProducaoLeiteController();
        desabilitarEdicao();
    }

    public void fNovoRegistro()
    {
        //
        this.objProducaoLeite = new ProducaoLeite();
        //Por padrão oculta o botão excluir
        btnExcluir.setEnabled(false);
        //Por padrão limpa o campo texto
        limparCampos();
        //Adiciona o status de edição
        this.edicao = false;
        //Seta o focu no campo de descrição ao abrir o formulário
        btnPesqAnimal.requestFocus();
    }

    public void fCarregaCadastro(int id)
    {
        //Se for passado um código por parâmetro, pesquisa no banco
        this.objProducaoLeite = this.objController.findById(id);
        //Carrega na tela o nome
        txtIdAnimal.setText(this.objProducaoLeite.getAnimal().getId().toString());
        txtNomeAnimal.setText(this.objProducaoLeite.getAnimal().getNome());

        jDateRegistro.setDate(this.objProducaoLeite.getDataHora());
        //Carrega na tela a quantidade
        txtQuantidade.setText(this.objProducaoLeite.getQuantidadeMl().toString());
        //Adiciona o status de edição
        this.edicao = true;
        //MOstra o botão excluir
        btnExcluir.setEnabled(true);
        //Seta o focu no campo de descrição ao abrir o formulário
        btnPesqAnimal.requestFocus();
    }

    public void fPesquisaAnimal()
    {
        if (frmPesqAnimal == null) {
            frmPesqAnimal = new FrmPesquisarAnimal();
            frmPesqAnimal.setModal(true);
        }

        if (frmPesqAnimal.isVisible()) {
            frmPesqAnimal.setVisible(false);
        } else {
            frmPesqAnimal.setLocationRelativeTo(null);
            frmPesqAnimal.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtNomeAnimal = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdAnimal = new javax.swing.JTextField();
        btnPesqAnimal = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jDateRegistro = new com.toedter.calendar.JDateChooser();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setTitle("Registro de Produção de Leite");
        setName(""); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Animal:");

        txtNomeAnimal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNomeAnimalActionPerformed(evt);
            }
        });

        txtQuantidade.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtQuantidadeActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade (ml):");

        jLabel7.setText("Data:");

        txtIdAnimal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIdAnimalActionPerformed(evt);
            }
        });
        txtIdAnimal.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtIdAnimalKeyPressed(evt);
            }
        });

        btnPesqAnimal.setText("...");
        btnPesqAnimal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPesqAnimalActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFecharActionPerformed(evt);
            }
        });

        jDateRegistro.setDateFormatString("dd/MM/yyyy HH:mm:ss");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesqAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesqAnimal)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir))
                    .addComponent(jDateRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

//        try {
//            String dataString = formatacao.ajustaDataHoraAMD(txtFormDataHora.getText());
//            Date data = new Date();
//            data = formatacao.formataDataHora(dataString);
//            objProducaoLeite.setDataHora(data);
            objProducaoLeite.setDataHora(jDateRegistro.getDate());
//        } catch (Exception ex) {
//            Logger.getLogger(FrmAnimalCadastro.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        Animal a = new Animal();
        a.setId(Integer.parseInt(txtIdAnimal.getText()));
        objProducaoLeite.setAnimal(a);

        objProducaoLeite.setQuantidadeMl(Integer.parseInt(txtQuantidade.getText()));

        objProducaoLeite.setIdUsuarioAlterou(UsuarioLogado.getId());

        try {
            //Verifica se deve adicionar ou atualizar um registro
            if (this.edicao) {
                //Chama o méotod INSERT do conttroler
                if (objController.update(objProducaoLeite)) {
                    //Limpa os campos
                    limparCampos();
                    //Fecha o formulário
                    this.setVisible(false);
                }
            } else {
                //Chama o méotod INSERT do conttroler
                if (objController.insert(objProducaoLeite)) {
                    //Limpa os campos
                    limparCampos();
                    //Fecha o formulário
                    this.setVisible(false);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valor informado para campo 'Dias de Validade' inválido!", "Atenção", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        objController.delete(objProducaoLeite);

        //Limpa os campos
        limparCampos();

        //Fecha o formulário
        this.setVisible(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAnimalActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtIdAnimalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIdAnimalActionPerformed
    {//GEN-HEADEREND:event_txtIdAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAnimalActionPerformed

    private void txtIdAnimalKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtIdAnimalKeyPressed
    {//GEN-HEADEREND:event_txtIdAnimalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAnimalKeyPressed

    private void btnPesqAnimalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPesqAnimalActionPerformed
    {//GEN-HEADEREND:event_btnPesqAnimalActionPerformed
        fPesquisaAnimal();
        this.txtIdAnimal.setText(String.valueOf(this.frmPesqAnimal.getId()));
        this.txtNomeAnimal.setText(String.valueOf(this.frmPesqAnimal.getNome()));
    }//GEN-LAST:event_btnPesqAnimalActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFecharActionPerformed
    {//GEN-HEADEREND:event_btnFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    public void limparCampos()
    {

        txtIdAnimal.setText("");
        txtNomeAnimal.setText("");
        txtQuantidade.setText("");
        jDateRegistro.setDate(null);
    }

    public void desabilitarEdicao()
    {
        //Desabilita a edição do componente
        txtIdAnimal.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesqAnimal;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateRegistro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txtIdAnimal;
    private javax.swing.JTextField txtNomeAnimal;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
