/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minhafazenda.view;

import com.minhafazenda.conttroler.RacaController;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author cleverton
 */
public class FrmRacaListagem extends javax.swing.JInternalFrame {

    private FrmRacaCadastro frm;
    private RacaController objController;

    /**
     * Creates new form FrmCategoriaListagem
     */
    public FrmRacaListagem() {
        initComponents();
        
        //Define o título para a janela
        this.setTitle("SGF - Relação de Raças");

        //Inicia o objeto de controller
        objController = new RacaController();
        //Carrega a lista no controller
        objController.findByAll();
        //Seta o controller no JTABLE
        jTableRaca.setModel(objController);
        jTableRaca.setName(title);

        //Personalização da JTABLE
        personalizarJtable();
    }

    public void pesquisar() {

        objController = new RacaController();
        //Carrega a lista de categorias no controller
        objController.findByAll(txtBusca.getText());
        //Seta o controller no JTABLE
        jTableRaca.setModel(objController);
        jTableRaca.setName(title);

        //Personalização da JTABLE
        personalizarJtable();

//        //Recebe o Session Factory do HIbernate
//        SessionFactory objSessionFactory = MinhaFazendaHibernateUtil.getSessionFactory();
//        //Abre um sessão
//        Session objSession = objSessionFactory.openSession();
//        //
//        Criteria objCriteria = objSession.createCriteria(Raca.class);
//        //Cria um
//        objCriteria.add(Restrictions.ilike("descricao", txtBusca.getText(), MatchMode.EXACT));
//        //Cria uma lista de Raças com o resultado da consulta
//        List<Raca> lstRaca = objCriteria.list();
//        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBUscar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRaca = new javax.swing.JTable();
        jBFechar = new javax.swing.JButton();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(728, 421));

        btnBUscar.setText("Buscar");
        btnBUscar.setName("btnBUscar"); // NOI18N
        btnBUscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBUscarActionPerformed(evt);
            }
        });

        txtBusca.setName(""); // NOI18N

        btnNovo.setText("Novo");
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        jTableRaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRaca.setEnabled(false);
        jScrollPane2.setViewportView(jTableRaca);

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBUscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBUscar)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBFechar)
                .addContainerGap())
        );

        txtBusca.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("Cadastro de Raças");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBUscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBUscarActionPerformed
        pesquisar();
    }//GEN-LAST:event_btnBUscarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if (frm == null) {
            frm = new FrmRacaCadastro();
            frm.setModal(true);
        }

        if (frm.isVisible()) {
            frm.setVisible(false);
        } else {
            frm.setVisible(true);
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBUscar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton jBFechar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRaca;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

    public void personalizarJtable() {
        TableColumnModel objColumn = jTableRaca.getColumnModel();
        objColumn.getColumn(0).setMaxWidth(100);

        jTableRaca.setPreferredScrollableViewportSize(jTableRaca.getPreferredSize());
        jTableRaca.setFillsViewportHeight(true);
    }
}
